### ISSUE TITLE
Photometry plot color is not indicative to specific filters

### ISSUE THREAD

**Issue by erezimm** [DurhamJohnAPaice/GEMTOM#2]
When uploading photometry to the target page the colors presented don't correlate to the bandpass and in some instances colors repeat for different filters. for example, in SN2024vjm (target #2), the color repeats for the J and V bands. Non detections have different colors than their detections.

The expected behavior is that there will be set colors for each defined filter. Color should never be repeated. Non-detections should be the same color as the detections.

<img width="675" alt="image" src="https://github.com/user-attachments/assets/37c1b346-5ac5-4446-8533-85cfd4237956">

Thanks!

**Comment by JohnAPaice** [comment]
Thanks for the report!

Colours will now be assigned based on the value of their string, so that both each filter will have a different colour, and the same filter on multiple sources will always have the same colour. Non-detections will also have the same colour as detections. Plus, BlackGEM filters (ugqriz) have the same colours as in the BlackGEM lightcurve plots.

See below!

![Screenshot 2024-11-13 at 12 46 37](https://github.com/user-attachments/assets/3ce6dbdf-b568-40a2-8d3e-017c9d9ba67f)
