### ISSUE TITLE
Page crashes after I try to add UVOT photometry

### ISSUE THREAD

**Issue by erezimm** [DurhamJohnAPaice/GEMTOM#3]
I tried adding a file at the following format of UVOT photometry:
time,filter,magnitude,error,limit,source
60630.8532,UVW1,20.0833,0.1513,22.769,UVOT

The page then crashed and now an error message appears when I try to go beck to the target:
https://gemtom.blackgem.org/targets/37/

![image](https://github.com/user-attachments/assets/df3e6bfc-72bd-450b-81ca-c27c0850a72b)

I think this might be related to undefined filters or something similar?

Thanks!
Erez

**Comment by DurhamJohnAPaice** [comment]
So, this is to do with my solution to an earlier issue ([#2](https://github.com/DurhamJohnAPaice/GEMTOM/issues/2)). My solution was to take the string of a band's name and create a hex value based on that string, then use that hex value as an RGB colour. That way, each band would have a unique colour, and if that band is used in multiple sources, it would always have that same colour.

It turned out that the hex value I was producing could be very small values, which python was reading as ###e-17 or similar. `rgba()` doesn't interpret numbers in this format, and that was the error.

I've solved it by checking each value for an 'e' character and changing its format if it's present, so it can interpret those values correctly now!

Thanks so much for the bug report!
